name: Build APK

on:
  push:
    paths:
      - .github/workflows/**

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: test file
        run: echo "hello world 123" > ${{ github.workspace }}/test.txt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: ${{ github.workspace }}/test.txt

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "text.txt"
          tag: test
          generateReleaseNotes: true
