name: Build APK

on:
  push:
    paths:
      - .github/workflows/**

  workflow_dispatch: 

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      # - name: test
      #   id: test
      #   run: echo "skip=true" >> $GITHUB_OUTPUT

      # - name: Exit if skip is true
      #   if: steps.test.outputs.skip == 'true'
      #   run: exit 1

      - name: Generate random tag
        id: tag
        run: echo "tag=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13)" > $GITHUB_OUTPUT

      - name: test file
        run: echo "hello world dsdsdfd123" > ${{ github.workspace }}/test.txt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: ${{ github.workspace }}/test.txt

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "test.txt"
          artifactContentType: text/plain
          tag: "123456"
          generateReleaseNotes: true
